### ISSUE TITLE
Got this error while trying to connect RDP. Any Solution?

### ISSUE THREAD

**Issue by anurag0345** [its-star-boi/ngrok-rdp#2]
![image](https://user-images.githubusercontent.com/68471938/233991030-59a2a976-2d10-4352-bccc-7f2949e2aefd.png)

**Comment by lovelykids** [comment]
0号服务器可能挂了，删了重新run

**Comment by its-star-boi** [comment]
This rdp closed in 6 hours or before 6 hours sometimes it will work 30 minutes
